# Generated by Django 5.2.14 on 2026-05-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyrouter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='fraud_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
